# Generated by Django 5.0.2 on 2026-01-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Activewear', 'Activewear'), ('Blazer', 'Blazer'), ('Cargo Pants', 'Cargo Pants'), ('Casual Shirt', 'Casual Shirt'), ('Coat', 'Coat'), ('Denim Jeans', 'Denim Jeans'), ('Dress', 'Dress'), ('Dress Pants', 'Dress Pants'), ('Formal Shirt', 'Formal Shirt'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket'), ('Joggers', 'Joggers'), ('Kids Wear', 'Kids Wear'), ('Pants', 'Pants'), ('Polo Shirt', 'Polo Shirt'), ('Puffy Vest', 'Puffy Vest'), ('Shirt', 'Shirt'), ('Shorts', 'Shorts'), ('Suit', 'Suit'), ('Sweater', 'Sweater'), ('Sweatshirt', 'Sweatshirt'), ('T-Shirt', 'T-Shirt'), ('Track Pants', 'Track Pants'), ('Vest', 'Vest'), ('Other', 'Other')], max_length=50),
        ),
    ]
